### ISSUE TITLE
messages 앱 이름의 중복

### ISSUE THREAD

**Issue by ghost** [OrmiFinal/gluv#30]
유닛 테스트 진행 시 아래와 같이 messages의 앱이 유니크하지 않아 동작하지 않는 문제가 있습니다.
```shell
(venv) PS D:\git\gluv\BE> python .\manage.py test
Traceback (most recent call last):
  File "D:\git\gluv\BE\manage.py", line 22, in <module>
    main()
  File "D:\git\gluv\BE\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "D:\git\gluv\venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "D:\git\gluv\venv\Lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
  File "D:\git\gluv\venv\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\git\gluv\venv\Lib\site-packages\django\apps\registry.py", line 93, in populate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: messages
```

이는 django.contrib.messages와 messages가 중복된다고 보는 것 같습니다. 
추후 논의가 필요합니다.

**Comment by ghost** [comment]
- 해결 방법으로 아래 두 가지 방법이 있을 것 같습니다.
```
1. messages를 다른 이름으로 변경
2. messages 앱 제거
  - Message 모델을 ChatRoom에 추가
```

**Comment by sengwoong** [comment]
ChatMessages 로바꾸는건 어떨까요?

**Comment by sengwoong** [comment]
Erd 상 ChatRoom 란 연결이 되어 있기 때문에 ChatRoomMessages 로 바꾸는것은 어떨까요?

**Comment by jmkim648** [comment]
django에서 앱 네이밍은 스네이크 케이스를 쓰는 것으로 알고 있습니다. ChatRoomMessages보다는 chat_messages나 chatroom_messages가 좋을 것 같네요

**Comment by ghost** [comment]
문제 해결되어 이슈 닫습니다.
- https://github.com/OrmiFinal/gluv/commit/6702d6a2b5c53f7e67c969ed01765ff14bb79f65
